pipeline {
    agent any
    stages {
        stage('compile') {
			steps {
                echo 'compiling..'
				git url: 'https://github.com/ashu071140/mule-pipeline.git'
				bat label: '', script: 'mvn clean'
            }
        }
    
        stage('unit-test') {
			steps {
                echo 'codereview..'
				bat label: '', script: 'mvn test'
            }
			
        }

        stage('package') {
			steps {
                echo 'metric-check..'
				bat label: '', script: 'mvn package'	
            }
			
        }
    }
}
